### PR TITLE
Godeepakm/add project flag

### PR DESCRIPTION
**Pull request by godeepakm**

### CODE REVIEW

**Review by zlav — APPROVED** [review]
Looks good to me! Thanks for putting this PR up

**Comment by cmboling** [comment]
This won't work until the app is built:

- [ ] `dist/index.js`
- [ ] `dist/index.js.map`

**Comment by cmboling** [comment]
✅ Test passed here: https://github.com/cmboling/fossa-action-project-flag-test/actions/runs/3945748661/jobs/6752920408

**Review by zlav — APPROVED** [review]
Still looks good!

**Comment by cmboling** [comment]
Woohoo! Finally 😆

**Pull request merged**
