### PR TITLE
[High priority] Use old-style import to fix FOSSA workflows

### LINKED ISSUE #22: fs undefined reading createWriteStream
Hello,

We recently noticed our builds failing the FOSSA scan due to the error below:

```
Run fossas/fossa-action@main
Error: There was an error fetching FOSSA CLI. TypeError: Cannot read properties of undefined (reading 'createWriteStream')
```

It appears to have been introduced [with v1.2.0](https://github.com/fossas/fossa-action/pull/19/files#diff-ad7faa452db2c39d404f11b420fb4ce38631c8b04c45f666320ba08fe371ff8a).

Could you please consider offering backward compatibility for build agents that don't support the new Node.js syntax?

Details of our GitHub Action runner below:
Operating System:
  Ubuntu

  LTS
Virtual Environment:
  Environment: ubuntu-20.04
  Version: 20220410.2

### PR DESCRIPTION
**Pull request by shubham1172**
Recently a change was introduced which has impacted repositories using this action via its main branch.

This PR reverts the `node:` style import to the old way, which is compatible with popular build agents. 
Additionally, I ran `yarn --frozen-lockfile` and `yarn build` to regenerate `./dist`.

Sample action run where it is working: https://github.com/shubham1172/dapr/runs/6061045569?check_suite_focus=true

Closes #22

### CODE REVIEW

**Comment by shubham1172** [comment]
@Serubin, @liftM can you please have a look at this?

**Comment by himynameisdave** [comment]
@shubham1172 thanks for fixing this, it was an oversight on my part. Just going to test these changes before cutting a new release.

**Comment by himynameisdave** [comment]
@shubham1172 this has been released in https://github.com/fossas/fossa-action/releases/tag/v1.3.0. Thanks again, you're a life saver!

**Comment by shubham1172** [comment]
Thank you for your quick help @himynameisdave! 🥳

**Pull request merged**
